services:
  workspacemanagement.api:
    image: ${DOCKER_REGISTRY-}workspacemanagementapi
    build:
      context: .
      dockerfile: WorkspaceManagement.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: workspace-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SecPass2026*
    volumes:
      - ./.containers/db:/var/lib/sqlServer/data 
    ports:
      - "1433:1433"
